export const CART_ACTION_TYPES = {
  SET_IS_CART_OPEN: "cart/SET_IS_CART_OPEN",
  ADD_PRODUCT_TO_CART: "cart/ADD_PRODUCT_TO_CART",
  SUBTRACT_PRODUCT_FROM_CART: "cart/SUBTRACT_PRODUCT_FROM_CART",
  REMOVE_PRODUCT_FROM_CART: "cart/REMOVE_PRODUCT_FROM_CART"
}